

//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"
#include "VideoSettingsPane.xaml.h"




void ::Win8Snes9x::VideoSettingsPane::InitializeComponent()
{
    if (_contentLoaded)
        return;

    _contentLoaded = true;

    // Call LoadComponent on ms-appx:///VideoSettingsPane.xaml
    ::Windows::UI::Xaml::Application::LoadComponent(this, ref new ::Windows::Foundation::Uri(L"ms-appx:///VideoSettingsPane.xaml"), ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);

    // Get the ComboBox named 'monitorComboBox'
    monitorComboBox = safe_cast<::Windows::UI::Xaml::Controls::ComboBox^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"monitorComboBox"));
    // Get the ComboBox named 'skipComboBox'
    skipComboBox = safe_cast<::Windows::UI::Xaml::Controls::ComboBox^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"skipComboBox"));
    // Get the ComboBox named 'powerSkipComboBox'
    powerSkipComboBox = safe_cast<::Windows::UI::Xaml::Controls::ComboBox^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"powerSkipComboBox"));
    // Get the ComboBox named 'turboSkipComboBox'
    turboSkipComboBox = safe_cast<::Windows::UI::Xaml::Controls::ComboBox^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"turboSkipComboBox"));
    // Get the ComboBox named 'aspectComboBox'
    aspectComboBox = safe_cast<::Windows::UI::Xaml::Controls::ComboBox^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"aspectComboBox"));
    // Get the Slider named 'imageScaleSlider'
    imageScaleSlider = safe_cast<::Windows::UI::Xaml::Controls::Slider^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"imageScaleSlider"));
    // Get the TextBlock named 'valueLabel'
    valueLabel = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"valueLabel"));
}

void ::Win8Snes9x::VideoSettingsPane::Connect(int connectionId, Platform::Object^ target)
{
    switch (connectionId)
    {
    case 1:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::ButtonBase^>(target))->Click +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Win8Snes9x::VideoSettingsPane::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&VideoSettingsPane::BackClick);
        break;
    case 2:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::Selector^>(target))->SelectionChanged +=
            ref new ::Windows::UI::Xaml::Controls::SelectionChangedEventHandler(this, (void (::Win8Snes9x::VideoSettingsPane::*)(Platform::Object^, Windows::UI::Xaml::Controls::SelectionChangedEventArgs^))&VideoSettingsPane::monitorComboBox_SelectionChanged_1);
        break;
    case 3:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::Selector^>(target))->SelectionChanged +=
            ref new ::Windows::UI::Xaml::Controls::SelectionChangedEventHandler(this, (void (::Win8Snes9x::VideoSettingsPane::*)(Platform::Object^, Windows::UI::Xaml::Controls::SelectionChangedEventArgs^))&VideoSettingsPane::skipComboBox_SelectionChanged_1);
        break;
    case 4:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::Selector^>(target))->SelectionChanged +=
            ref new ::Windows::UI::Xaml::Controls::SelectionChangedEventHandler(this, (void (::Win8Snes9x::VideoSettingsPane::*)(Platform::Object^, Windows::UI::Xaml::Controls::SelectionChangedEventArgs^))&VideoSettingsPane::powerSkipComboBox_SelectionChanged_1);
        break;
    case 5:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::Selector^>(target))->SelectionChanged +=
            ref new ::Windows::UI::Xaml::Controls::SelectionChangedEventHandler(this, (void (::Win8Snes9x::VideoSettingsPane::*)(Platform::Object^, Windows::UI::Xaml::Controls::SelectionChangedEventArgs^))&VideoSettingsPane::turboSkipComboBox_SelectionChanged_1);
        break;
    case 6:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::Selector^>(target))->SelectionChanged +=
            ref new ::Windows::UI::Xaml::Controls::SelectionChangedEventHandler(this, (void (::Win8Snes9x::VideoSettingsPane::*)(Platform::Object^, Windows::UI::Xaml::Controls::SelectionChangedEventArgs^))&VideoSettingsPane::aspectComboBox_SelectionChanged_1);
        break;
    case 7:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::RangeBase^>(target))->ValueChanged +=
            ref new ::Windows::UI::Xaml::Controls::Primitives::RangeBaseValueChangedEventHandler(this, (void (::Win8Snes9x::VideoSettingsPane::*)(Platform::Object^, Windows::UI::Xaml::Controls::Primitives::RangeBaseValueChangedEventArgs^))&VideoSettingsPane::imageScaleSlider_ValueChanged_1);
        break;
    }
    (void)connectionId; // Unused parameter
    (void)target; // Unused parameter
    _contentLoaded = true;
}

